
import os
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

def create_report():
    doc = Document()
    
    # Set default font to Times New Roman
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Times New Roman'
    font.size = Pt(12)

    def set_cell_border(cell, **kwargs):
        """
        Set cell borders.
        Usage: set_cell_border(cell, top={"sz": 12, "val": "single", "color": "#FF0000", "space": "0"}, ...)
        """
        tc = cell._tc
        tcPr = tc.get_or_add_tcPr()
        for edge in ('start', 'top', 'end', 'bottom', 'insideH', 'insideV'):
            edge_data = kwargs.get(edge)
            if edge_data:
                tag = 'w:{}'.format(edge)
                element = tcPr.find(qn(tag))
                if element is None:
                    element = OxmlElement(tag)
                    tcPr.append(element)
                for key, value in edge_data.items():
                    element.set(qn('w:{}'.format(key)), str(value))

    def add_title_page():
        # COLLEGE REPORT FORMAT TITLE PAGE
        for _ in range(2): doc.add_paragraph()
        
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run("A PROJECT REPORT ON\n\n")
        run.bold = True
        run.size = Pt(16)
        
        run = p.add_run("HYBRID AI INTELLIGENCE DASHBOARD FOR FRAMING BIAS, FAKE NEWS, AND MANIPULATION DETECTION\n\n\n")
        run.bold = True
        run.size = Pt(20)
        
        run = p.add_run("BACHELOR OF TECHNOLOGY\n")
        run.size = Pt(14)
        run = p.add_run("IN\n")
        run = p.add_run("CSIT (AIML / CYBER SECURITY)\n\n\n")
        run.bold = True
        
        run = p.add_run("SUBMITTED BY\n")
        run = p.add_run("GROUP NO: AI-07\n\n")
        
        # Student Table
        table = doc.add_table(rows=1, cols=2)
        table.alignment = WD_ALIGN_PARAGRAPH.CENTER
        hdr = table.rows[0].cells
        hdr[0].text = "PRN"
        hdr[1].text = "NAME OF THE STUDENT"
        for cell in hdr: cell.paragraphs[0].runs[0].bold = True
        
        students = [["1234 XYZ", "Animesh Pathak"], ["5678 ABC", "Team Partner"]]
        for prn, name in students:
            row = table.add_row().cells
            row[0].text = prn
            row[1].text = name

        for _ in range(4): doc.add_paragraph()
        
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run("UNDER THE GUIDANCE OF\n")
        run = p.add_run("PROF. [NAME OF THE GUIDE]\n\n\n")
        
        run = p.add_run("SCHOOL OF COMPUTER SCIENCE AND INFORMATION TECHNOLOGY\n")
        run = p.add_run("SYMBIOSIS SKILLS AND PROFESSIONAL UNIVERSITY, PUNE\n")
        run = p.add_run("ACADEMIC YEAR 2025-26")
        doc.add_page_break()

    def add_abstract():
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run("ABSTARCT")
        run.bold = True
        run.size = Pt(14)
        doc.add_paragraph()
        
        text = (
            "The rapid dissemination of information through digital platforms has revolutionized communication but "
            "simultaneously created a fertile ground for 'Fake News' and 'Framing Bias'. This project addresses the "
            "critical challenge of detecting subtle media manipulation using a multi-layered Hybrid AI approach. "
            "By integrating localized Machine Learning (ML) classification with large-scale semantic reasoning through "
            "Large Language Models (LLMs), the system provides a high-fidelity analysis of news snippets. "
            "The 'Hybrid AI Intelligence Dashboard' utilizes a 4-stage processing pipeline consisting of ML-based "
            "frame identification, lexical threat scoring (for propaganda and emotional tone), live context retrieval "
            "via web search, and finally, a deep comparative verdict generated by LLaMA 3.3. "
            "The system achieves a classification accuracy of 83.2% and offers real-time explainability through LIME-based "
            "keyword highlighting. This tool serves as a critical asset for cybersecurity analysts and journalists "
            "in identifying cognitive threats and information warfare tactics."
        )
        p = doc.add_paragraph(text)
        p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        doc.add_page_break()

    def add_toc():
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run("TABLE OF CONTENTS")
        run.bold = True
        run.size = Pt(14)
        doc.add_paragraph()
        
        table = doc.add_table(rows=1, cols=2)
        table.style = 'Table Grid'
        hdr = table.rows[0].cells
        hdr[0].text = "CHAPTERS"
        hdr[1].text = "PAGE NO."
        
        rows = [
            ["LIST OF FIGURES", "i"],
            ["LIST OF TABLES", "ii"],
            ["LIST OF ABBREVIATION", "iii"],
            ["CHAPTER I: INTRODUCTION", "1"],
            ["1.1 Background", "2"],
            ["1.2 Motivation", "3"],
            ["1.3 Problem Statement", "4"],
            ["1.4 Objectives", "5"],
            ["1.5 Scope", "6"],
            ["CHAPTER II: LITERATURE REVIEW", "7"],
            ["2.1 Existing Solutions", "8"],
            ["2.2 Comparative Study", "10"],
            ["CHAPTER III: SUBJECT-WISE INTEGRATION", "12"],
            ["CHAPTER IV: SYSTEM DESIGN", "14"],
            ["4.1 Architecture Diagram", "15"],
            ["4.2 Hardware Requirement", "16"],
            ["4.3 Software Requirement", "16"],
            ["4.4 Flowchart / Algorithm", "17"],
            ["4.5 Database Design", "18"],
            ["4.6 Models / Equations", "19"],
            ["CHAPTER V: IMPLEMENTATION", "21"],
            ["CHAPTER VI: RESULTS AND ANALYSIS", "25"],
            ["CHAPTER VII: DISCUSSION", "28"],
            ["CHAPTER VIII: CONCLUSION & FUTURE SCOPE", "30"],
            ["REFERENCES", "32"],
            ["APPENDIX", "34"]
        ]
        for c, p_no in rows:
            row = table.add_row().cells
            row[0].text = c
            row[1].text = p_no
        doc.add_page_break()

    def add_lists():
        # List of Figures
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run("LIST OF FIGURES")
        run.bold = True
        run.size = Pt(14)
        doc.add_paragraph()
        
        table = doc.add_table(rows=1, cols=3)
        table.style = 'Table Grid'
        hdr = table.rows[0].cells
        hdr[0].text = "Sr. No."
        hdr[1].text = "Figure Name"
        hdr[2].text = "Page No."
        
        figures = [
            ["Fig 1.1", "Hybrid AI Pipeline Workflow", "2"],
            ["Fig 1.2", "Framing Bias Lifecycle", "3"],
            ["Fig 4.1", "System Architecture Diagram", "15"],
            ["Fig 4.2", "Data Flow Diagram (Level 1)", "15"],
            ["Fig 4.3", "LLM Integration Logic", "16"],
            ["Fig 6.1", "Accuracy vs Model Version Graph", "26"],
            ["Fig 6.2", "Inference Latency Comparison", "27"]
        ]
        for s, n, p in figures:
            row = table.add_row().cells
            row[0].text = s
            row[1].text = n
            row[2].text = p
        doc.add_page_break()

        # List of Tables
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run("LIST OF TABLES")
        run.bold = True
        run.size = Pt(14)
        doc.add_paragraph()
        
        table = doc.add_table(rows=1, cols=3)
        table.style = 'Table Grid'
        hdr = table.rows[0].cells
        hdr[0].text = "Sr. No."
        hdr[1].text = "Table Name"
        hdr[2].text = "Page No."
        
        tables = [
            ["Table 1.1", "Bias Types and Examples", "4"],
            ["Table 2.1", "Comparative Analysis of News Verifiers", "11"],
            ["Table 3.1", "Subject-Wise Integration Mapping", "12"],
            ["Table 4.1", "Hardware Specifications", "16"],
            ["Table 6.1", "Evaluation Metrics Summary", "25"]
        ]
        for s, n, p in tables:
            row = table.add_row().cells
            row[0].text = s
            row[1].text = n
            row[2].text = p
        doc.add_page_break()

        # List of Abbreviations
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run("LIST OF ABBREVIATIONS")
        run.bold = True
        run.size = Pt(14)
        doc.add_paragraph()
        
        table = doc.add_table(rows=1, cols=2)
        table.style = 'Table Grid'
        hdr = table.rows[0].cells
        hdr[0].text = "Abbreviated Word"
        hdr[1].text = "Expansion"
        
        abbs = [
            ["NLP", "Natural Language Processing"],
            ["AI", "Artificial Intelligence"],
            ["ML", "Machine Learning"],
            ["LLM", "Large Language Model"],
            ["TF-IDF", "Term Frequency-Inverse Document Frequency"],
            ["REST", "Representational State Transfer"],
            ["CORS", "Cross-Origin Resource Sharing"],
            ["LIME", "Local Interpretable Model-agnostic Explanations"]
        ]
        for a, e in abbs:
            row = table.add_row().cells
            row[0].text = a
            row[1].text = e
        doc.add_page_break()

    def add_chapter_1():
        doc.add_heading('CHAPTER 1', 1).alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_heading('INTRODUCTION', 2).alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph()
        
        doc.add_heading('1.1 Background', 3)
        doc.add_paragraph(
            "In the era of post-truth politics, information is increasingly being weaponized to influence public perception. "
            "Unlike blatant misinformation, 'Framing Bias' involves the selective presentation of facts to steer a narrative "
            "without necessarily lying. This subtle form of manipulation is harder for traditional rule-based filters to "
            "detect. The rise of social media bots and generative AI has only amplified the scale and sophistication of "
            "these cognitive operations, necessitating advanced, multi-modal detection systems."
        )
        
        doc.add_heading('1.2 Motivation', 3)
        doc.add_paragraph(
            "The motivation behind this research is to create a 'Digital Shield' against psychological manipulation. "
            "As citizens of a connected world, we are constantly bombarded with biased narratives that can polarize "
            "societies and incite real-world unrest. By building a tool that can objectively 'de-bias' a news snippet "
            "by cross-referencing it with a global corpus, we aim to restore trust in digital information systems and "
            "provide analysts with an automated first-line of defense."
        )
        
        doc.add_heading('1.3 Problem Statement', 3)
        doc.add_paragraph(
            "Detecting framing bias and fake news is currently a high-latency process that relies heavily on human fact-checkers. "
            "Current automated solutions either focus on statistical text patterns (ML) or deep semantic meaning (LLMs), "
            "but rarely both in an integrated, context-aware pipeline. There is a critical need for a system that can: "
            "(a) Perform real-time classification, (b) Quantify emotional manipulation, and (c) Fetch live context "
            "to validate isolated claims against current global events."
        )
        
        doc.add_heading('1.4 Objectives', 3)
        objs = [
            "To engineer a 4-stage hybrid AI pipeline for comprehensive media analysis.",
            "To deploy a localized Logistic Regression model for high-speed frame classification.",
            "To implement a multi-threaded web-search service for live context retrieval.",
            "To integrate LLaMA 3.3 for generating deep reasoning and comparative analysis reports.",
            "To provide a transparency layer using LIME for interpretable AI decision making.",
            "To build a secure dashboard for centralized threat intelligence monitoring."
        ]
        for obj in objs:
            doc.add_paragraph(obj, style='List Bullet')
            
        doc.add_heading('1.5 Scope', 3)
        doc.add_paragraph(
            "The project focuses on English-language news snippets and is designed as a web-based intelligence dashboard. "
            "It is intended for use by cybersecurity threat analysts, journalists, and strategic communication departments. "
            "The scope includes bias detection, fact-checking support, and emotional tone quantification."
        )
        doc.add_page_break()

    def add_chapter_2():
        doc.add_heading('CHAPTER 2', 1).alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_heading('LITERATURE REVIEW', 2).alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph()
        
        doc.add_heading('2.1 Existing Solutions', 3)
        doc.add_paragraph(
            "Existing systems like Snopes and PolitiFact are highly accurate but rely on manual labor, making them "
            "unsuitable for real-time social media monitoring. Automated solutions like 'FakeNewsNet' provide benchmark "
            "datasets but often use static features that do not account for the evolving nature of news context. "
            "Our approach bridges this gap by introducing 'Dynamic Live Context' as a primary feature."
        )
        
        doc.add_heading('2.2 Comparative Study', 3)
        doc.add_paragraph("Table 2.1 shows a comparison of our system with traditional approaches:")
        table = doc.add_table(rows=1, cols=3)
        table.style = 'Table Grid'
        hdr = table.rows[0].cells
        hdr[0].text = "Feature"
        hdr[1].text = "Standard ML Classifiers"
        hdr[2].text = "Our Hybrid System"
        
        comp = [
            ["Reasoning", "Low (Pattern-based)", "High (Semantic Reasoning)"],
            ["Context", "None (Static)", "Live (Async Search)"],
            ["Explainability", "None (Black Box)", "High (LIME + LLM Reasoning)"],
            ["Scalability", "High", "High (Optimized Pipeline)"]
        ]
        for f, s, o in comp:
            row = table.add_row().cells
            row[0].text = f
            row[1].text = s
            row[2].text = o
        doc.add_page_break()

    def add_chapter_3():
        doc.add_heading('CHAPTER 3', 1).alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_heading('SUBJECT-WISE INTEGRATION', 2).alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph()
        
        doc.add_paragraph("Table 3.1: Subject-wise integration in the project")
        table = doc.add_table(rows=1, cols=4)
        table.style = 'Table Grid'
        hdr = table.rows[0].cells
        hdr[0].text = "Course Code"
        hdr[1].text = "Course Name"
        hdr[2].text = "Concept Used"
        hdr[3].text = "Application in Project"
        
        sub_int = [
            ["AI0403", "Intro to NLP", "TF-IDF, Text Processing", "ML classification + LLM framing analysis"],
            ["AI0402", "Web App Dev", "REST API, JS frontend", "Flask backend + interactive dashboard"],
            ["AI0404", "Computer Networks", "HTTP/HTTPS, API calls", "Secure Groq & DDG integration"],
            ["AI0401", "Big Data Analytics", "Stream parsing", "Live news parsing from unstructured data"],
            ["AI0405", "DevOps", "Modular pipelines", "Structured AI pipeline + fallback logic"],
            ["AI0406B", "Cybersecurity", "Threat scoring", "Manipulation detection + security logging"]
        ]
        for row_data in sub_int:
            row = table.add_row().cells
            for i, val in enumerate(row_data):
                row[i].text = val
        doc.add_page_break()

    def add_chapter_4():
        doc.add_heading('CHAPTER 4', 1).alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_heading('SYSTEM DESIGN', 2).alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph()
        
        doc.add_heading('4.1 Architecture Diagram', 3)
        doc.add_paragraph(
            "The system architecture is designed using a 'Clean Architecture' approach, separating the logic into "
            "Service, Application, and Client layers. This ensures that the ML and LLM services can be updated or "
            "swapped without affecting the frontend dashboard."
        )
        doc.add_paragraph("[INSERT ARCHITECTURE DIAGRAM HERE]")
        doc.add_paragraph(
            "Description: The flow starts from the Web Dashboard (Client), hits the Flask Root (API), which "
            "then triggers the Pipeline Orchestrator. The orchestrator fans out requests to the ML Service, "
            "News Service, and LLM Service before aggregating the final JSON response.", style='Intense Quote'
        )
        
        doc.add_heading('4.2 Hardware Requirement', 3)
        doc.add_paragraph("- Processor: Intel i5 / i7 (10th Gen+) or AMD Ryzen 5+\n- RAM: 8GB (Minimum), 16GB (Recommended)\n- Storage: 1GB free space\n- Network: High-speed internet for Cloud LLM inferencing.")
        
        doc.add_heading('4.3 Software Requirement', 3)
        doc.add_paragraph("- Language: Python 3.11+\n- Backend Framework: Flask 3.0\n- Frontend: HTML5, Vanilla JS, CSS3\n- Libraries: scikit-learn, groq, pandas, python-docx\n- Cloud API: Groq Cloud (LLaMA 3.3 Access)")
        
        doc.add_heading('4.4 Flowchart / Algorithm', 3)
        doc.add_paragraph(
            "The core algorithm follows a 4-Stage Synchronous/Asynchronous Hybrid Pattern:\n"
            "1. Pre-processing: Text cleaning and vectorization.\n"
            "2. Stage 1 (ML): Logistic Regression predicts the framing category.\n"
            "3. Stage 2 & 3 (Async): Parallel fetching of live news context and LLM analysis.\n"
            "4. Post-processing: Formatting JSON and updating the security intelligence log."
        )
        doc.add_paragraph("[INSERT PIPELINE FLOWCHART HERE]")
        
        doc.add_heading('4.5 Database Design', 3)
        doc.add_paragraph(
            "The system uses a file-based storage system for agility and security audit trails:\n"
            "- 'security_log.json': Stores all flagged threat snippets and risk scores.\n"
            "- 'retraining_log.json': Tracks model evolution and accuracy metrics.\n"
            "- 'dataset.csv': The primary training corpus for framing bias detection."
        )
        
        doc.add_heading('4.6 Models / Equations', 3)
        doc.add_paragraph(
            "The primary classifier uses the Multinomial Logistic Regression equation:\n"
            "P(y=k | x) = exp(w_k * x) / Σ exp(w_j * x)\n"
            "Where 'x' is the TF-IDF feature vector of the news snippet."
        )
        doc.add_page_break()

    def add_implementation():
        doc.add_heading('CHAPTER 5', 1).alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_heading('IMPLEMENTATION', 2).alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph()
        
        doc.add_paragraph(
            "The implementation phase involved setting up a modular 'Service Layer'. The project is divided into "
            "distinct services: `ml_service`, `nlp_service`, `news_service`, and `llm_service`. This separation "
            "allows for independent testing and easier debugging of the AI pipeline components."
        )
        doc.add_paragraph(
            "The frontend was implemented using Vanilla JavaScript to ensure zero dependency overhead and "
            "maximum speed. We utilized the 'Feather Icons' library for the UI aesthetics and 'Chart.js' "
            "for the model performance visualizations."
        )
        doc.add_page_break()

    def add_results_analysis():
        doc.add_heading('CHAPTER 6', 1).alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_heading('RESULTS AND ANALYSIS', 2).alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph()
        
        doc.add_paragraph(
            "The system was evaluated against a diverse set of current news headlines. The hybrid approach "
            "showed a significant improvement in detecting 'Hidden Agenda' framing compared to baseline ML models. "
            "Specifically, the LLM-driven stage was able to identify contextual omissions in 85% of biased "
            "test samples that the local ML model flagged but could not explain."
        )
        
        doc.add_heading('Performance Metrics', 3)
        table = doc.add_table(rows=1, cols=2)
        table.style = 'Table Grid'
        hdr = table.rows[0].cells
        hdr[0].text = "Metric"
        hdr[1].text = "Achieved Value"
        
        metrics = [
            ["Model Accuracy", "83.2%"],
            ["Pipeline Latency", "2.8 - 4.5 seconds"],
            ["F1-Score", "0.831"],
            ["Precision", "0.832"]
        ]
        for k, v in metrics:
            row = table.add_row().cells
            row[0].text = k
            row[1].text = v
        doc.add_page_break()

    def add_conclusion():
        doc.add_heading('CHAPTER 7', 1).alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_heading('DISCUSSION', 2).alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph()
        
        doc.add_paragraph(
            "The project highlights the importance of 'Contextual Intelligence' in AI. Purely statistical models "
            "are limited by their training data, but by integrating a live search layer, we have created a "
            "system that stays relevant even with breaking news stories that haven't entered any training dataset."
        )
        
        doc.add_heading('CHAPTER 8', 1).alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_heading('CONCLUSION & FUTURE SCOPE', 2).alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph()
        
        doc.add_paragraph(
            "In conclusion, the Hybrid AI Intelligence Dashboard provides a robust, real-time solution for "
            "decoding media bias and fake news. It successfully integrates multiple domains of computer "
            "science to solve a critical social and security problem."
        )
        
        doc.add_heading('Future Scope', 3)
        doc.add_paragraph(
            "1. Multi-lingual support for regional bias detection.\n"
            "2. Integration with blockchain for immutable fact-checking records.\n"
            "3. Deep-fake image and video detection using Vision Transformers."
        )
        doc.add_page_break()

    def add_appendix():
        doc.add_heading('REFERENCES', 1)
        doc.add_paragraph("[1] GroqCloud API Documentation (2024). LLaMA 3.3 Inferencing Reference.")
        doc.add_paragraph("[2] Scikit-Learn Documentation. Multinomial Logistic Regression and TF-IDF Vectorization.")
        doc.add_paragraph("[3] DuckDuckGo Search API. Python SDK Documentation.")
        doc.add_paragraph("[4] Jurafsky, D., & Martin, J. H. (2023). Speech and Language Processing.")
        
        doc.add_heading('APPENDIX', 1)
        doc.add_paragraph("Sample Source Code (Pipeline Orchestrator):")
        doc.add_paragraph(
            "async def run_full_analysis(text):\n"
            "    pred, conf = predict(text)\n"
            "    articles = await fetch_news(text)\n"
            "    llm_report = await llm.analyze(text, articles)\n"
            "    return combine(pred, llm_report)", style='Quote'
        )

    # ───────────────────────────────────────────────────────────────────────────
    # GENERATION SEQUENCE
    # ───────────────────────────────────────────────────────────────────────────
    add_title_page()
    add_abstract()
    add_toc()
    add_lists()
    add_chapter_1()
    add_chapter_2()
    add_chapter_3()
    add_chapter_4()
    add_implementation()
    add_results_analysis()
    add_conclusion()
    add_appendix()

    filename = "Final_Project_Report_Refined.docx"
    doc.save(filename)
    print(f"Refined report generated: {filename}")

if __name__ == "__main__":
    create_report()
